### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by walter-grace** [aj-may/docker-proxy#6]
I cannot seem to use the curl /bash command to install docker-proxy ; any suggestions? It is showing it is installed sometimes but when I run docker-proxy nothing works

**Comment by aj-may** [comment]
Sorry, this script will not work on windows.  I will note this in the README.

If you are willing to contribute, I am looking to add windows support to my new project https://github.com/aj-may/dotdocker

**Comment by aj-may** [comment]
Updated the README to call out that this tool is for MacOS.  Looking for help building windows support in <https://github.com/aj-may/dotdocker>.
